const GET_PROVINSI = "GET_PROVINSI";
const GET_KABUPATEN = "GET_KABUPATEN";
const GET_KECAMATAN = "GET_KECAMATAN";
const GET_KELURAHAN = "GET_KELURAHAN";

export { GET_PROVINSI, GET_KABUPATEN, GET_KECAMATAN, GET_KELURAHAN };
